<?php
require_once("config.php");
require_once("functions.php");
require_once("database.php");
require_once("tabla.php");
require_once("user.php");
require_once("photo.php");
require_once("session.php");
?>
